resolution: "480p"
aspect_ratio: "9:16"
num_frames: 48
fps: 24
frame_interval: 1

seed: 42
multi_resolution: "STDiT2"
dtype: "bf16"
condition_frame_length: 5
align: 5
num_sampling_steps: 30
cfg_scale: 7.0
aes: 6.5

# speedup
flash_attn: True

# fvd
spatial_skip: True
spatial_threshold: [540, 920]  # 20/30
spatial_gap: 2
spatial_block: [0, 28]
temporal_skip: True
temporal_threshold: [540, 960]  # 24/30
temporal_gap: 4
cross_skip: True
cross_threshold: [540, 960]  # 24/30
cross_gap: 6
# diffusion_skip: True
# diffusion_skip_timestep: [1,1,1,0,0,0,0,0,0,0]

# eval
eval: True
eval_dataset: ./evaluations/fastvideodiffusion/datasets/webvid_selected.csv
save_dir: ./evaluations/fastvideodiffusion/samples/opensora/sample_fvd
