# video
num_frames: 16
frame_interval: 3
fps: 24
image_size: [240, 426]
num_samples: 1

# runtime
batch_size: 1
save_dir: "./samples/opensora"
seed: 42
dtype: "bf16"

# model
model_pretrained_path: "hpcai-tech/OpenSora-STDiT-v2-stage3"

# scheduler
scheduler_num_sampling_steps: 100
scheduler_cfg_scale: 7.0

# speedup
enable_flashattn: True
enable_t5_speedup: True

# skip
spatial_skip: True
spatial_threshold: 700
spatial_gap: 3
temporal_skip: True
temporal_threshold: 700
temporal_gap: 5
cross_skip: True
cross_threshold: 700
cross_gap: 5
